### ISSUE TITLE
Like hider not working with new Twitter design

### ISSUE THREAD

**Issue by hindman** [rendall/twitter-like-hider#1]
The extension appears to not work correctly with the new Twitter design: as soon as the new design rolled out, I started seeing many likes in my feed.

Is an update in the works? I hope so -- this is a valuable utility and I appreciate your work on it. Thanks for taking a look.

**Comment by hindman** [comment]
Problem seems resolved lately -- probably on the Twitter side. Closing.

**Comment by rendall** [comment]
Twitter has completely revamped its presentation, and so this needs some refactoring.

**Comment by rendall** [comment]
Hmm.  I cannot see any 'liked' or 'follows' posts in my Twitter feed on Chrome at all, even without the extension. Can someone verify? If true, I may need to close this extension as obsolete.

I do see them in my Android Twitter app, though.

**Comment by rendall** [comment]
Gonna close this and open a new issue. Thanks!
