### ISSUE TITLE
Obsolete?

### ISSUE THREAD

**Issue by rendall** [rendall/twitter-like-hider#2]
It may be that Twitter has eliminated this type of post from their website.

**Comment by rendall** [comment]
If anyone can leave a comment confirming or refuting that Twitter no longer has 'like' or 'follows' posts in the Chrome feed?

**Comment by bluepotioncoding** [comment]
This might come in late as I just found your plugin now but my public twitter account literally floods 90+% of my timeline with "somebody liked" tweets of people I dont follow.

Happens on Chrome and Firefox alike. I'm now highly dependend of your plugin (works perfectly) so thanks a lot for the great work @rendall !

**Comment by rendall** [comment]
Thanks.  I got a report that some areas of the world have a different version that's messing with it. Unfortunately I'm not able to see it.  Anyway, I'll close this.
