### ISSUE TITLE
Hide tweets from follower's follower's?

### ISSUE THREAD

**Issue by HarrisonMc555** [rendall/twitter-like-hider#3]
Thanks for the great tool! I have an idea for an improvement. Would you be willing to accept a pull request for this? I'm unfamiliar with Chrome extensions but could probably figure it out if you're willing to accept the addition.

I have recently seen many tweets like the following. If I follow Bob, and Bob follows Carol, then I'll see tweets labeled "Bob follows Carol".

It would be great to hide these tweets in addition to the "liked" tweets.

Let me know if you'd be willing to incorporate this!

**Comment by rendall** [comment]
Hi @HarrisonMc555 

I am astonished that I didn't see this yet. My apologies.  The extension _should_ already do this. For some reason, my personal Twitter account no longer shows this in Chrome, so it's hard for me to fix it.

If you're still open to this PR, I absolutely would accept it.

As a head start, you would probably alter this line in `content_script.js`:
`const TWEET_FOLLOWS_SELECTOR = ".tweet-context.with-icn span.Icon.Icon--small.Icon--follower";`

This is the CSS selector for the _follows_ tweets, that _should_ uniquely determine them.  When Twitter updates its layout, sometimes the extension breaks.

Send me an email to my [personal email ](mailto:rendall@gmail.com) if you want to communicate more about this, especially if you finish the PR and I take more than a day or two to respond.

**Comment by rendall** [comment]
Hi @HarrisonMc555 

I think the latest version (1.6.1) resolves this issue, so I'm going to go ahead and close it. If I'm wrong, please feel free to reopen.

Happy New Year!
