### ISSUE TITLE
Likes on tweets sent by followees are hidden

### ISSUE THREAD

**Issue by tlaak** [rendall/twitter-like-hider#9]
When you follow "TweeterOne" and "TweeterTwo" and "TweeterOne" likes a tweet sent by "TweeterTwo", the extension will hide it. You might actually want to see their tweet.

If this option was configurable by passing a list of usernames (my followees) to the extension, it would leave it to the extension user to decide whether they want to hide these tweets or not.

**Comment by rendall** [comment]
How would that work best, do you think? Does the extension fetch the user list, or does the user whitelist specific names?

The _followers_ page URL would be pretty easy to find given a logged-in user (e.g. mine: <https://twitter.com/rendall/following>)  but it's also infinite scroll, so I'm not sure it's easy to fetch... Maybe asking a user to go to that page and scroll through it slowly, then the extension could assemble the user's follows?

I considered the Twitter API as a possible option, until I actually looked at it. Authentication is pretty complicated: https://developer.twitter.com/en/docs/twitter-api/users/follows/quick-start/follows-lookup

**Comment by tlaak** [comment]
Fetching the user list automatically would probably be the option which is the most user friendly. Many follow hundreds or even thousands of accounts and adding exclusions manually might be quite a lot of work. I don't think manual scrolling is very user friendly.

Would adding Twitter API be worth the effort if it makes developing other useful features easier?

**Comment by rendall** [comment]
Hey Timo.

To be fair to the users, I have decided to sunset this extension and stop supporting it. Twitter has changed quite a bit and I no longer have the interest. I can recommend the "Following" tab, as it seems to have similar functionality.  Good luck and hope to see you around Twitter.

-- Rendall
